[crate_roots]
"assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)" = "/Users/michaelzaikin/raito/packages/assumevalid/src"
"bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/stwo-cairo-knss3ccrk4ktk/d09a2cfd/stwo_cairo_verifier/crates/bounded_int/src"
"consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)" = "/Users/michaelzaikin/raito/packages/consensus/src"
"ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/ripemd160_cairo-9tlsggif2vsdg/833e07d/src"
"sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/sha1_cairo-ijhp98qgkbdk8/2b65bc0/src"
"shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/shinigami-44ae3sm69mj68/1963116/packages/engine/src"
"shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/shinigami-44ae3sm69mj68/1963116/packages/utils/src"
"stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/stwo-cairo-knss3ccrk4ktk/d09a2cfd/stwo_cairo_verifier/crates/cairo_air/src"
"stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/stwo-cairo-knss3ccrk4ktk/d09a2cfd/stwo_cairo_verifier/crates/constraint_framework/src"
"stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)" = "/Users/michaelzaikin/Library/Caches/com.swmansion.scarb/registry/git/checkouts/stwo-cairo-knss3ccrk4ktk/d09a2cfd/stwo_cairo_verifier/crates/verifier_core/src"
"utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)" = "/Users/michaelzaikin/raito/packages/utils/src"

[config.global]
edition = "2024_07"
version = "0.1.0"
cfg_set = [[
    "target",
    "executable",
]]

[config.global.dependencies.assumevalid]
discriminator = "assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)"

[config.global.dependencies.bounded_int]
discriminator = "bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.global.dependencies.consensus]
discriminator = "consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)"

[config.global.dependencies.ripemd160]
discriminator = "ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)"

[config.global.dependencies.sha1]
discriminator = "sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)"

[config.global.dependencies.shinigami_engine]
discriminator = "shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.global.dependencies.shinigami_utils]
discriminator = "shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.global.dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.global.dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.global.dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.global.dependencies.utils]
discriminator = "utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)"

[config.global.experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)"]
name = "assumevalid"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    [
    "feature",
    "default",
],
    [
    "feature",
    "syscalls",
],
    [
    "target",
    "executable",
],
]

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)".dependencies.assumevalid]
discriminator = "assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)"

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)".dependencies.consensus]
discriminator = "consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)"

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)".dependencies.utils]
discriminator = "utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)"

[config.override."assumevalid 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/assumevalid/Scarb.toml)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"]
name = "bounded_int"
edition = "2023_10"
version = "0.1.0"

[config.override."bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.bounded_int]
discriminator = "bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)"]
name = "consensus"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    [
    "feature",
    "default",
],
    [
    "feature",
    "syscalls",
],
    [
    "target",
    "executable",
],
]

[config.override."consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)".dependencies.consensus]
discriminator = "consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)"

[config.override."consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)".dependencies.shinigami_engine]
discriminator = "shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.override."consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)".dependencies.utils]
discriminator = "utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)"

[config.override."consensus 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/consensus/Scarb.toml)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)"]
name = "ripemd160"
edition = "2024_07"
version = "0.1.0"

[config.override."ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)".dependencies.ripemd160]
discriminator = "ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)"

[config.override."ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)"]
name = "sha1"
edition = "2024_07"
version = "0.1.0"

[config.override."sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)".dependencies.sha1]
discriminator = "sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)"

[config.override."sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"]
name = "shinigami_engine"
edition = "2024_07"
version = "0.1.0"

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".dependencies.ripemd160]
discriminator = "ripemd160 0.1.0 (git+https://github.com/j1mbo64/ripemd160_cairo.git#833e07d7d074d4ee51ceb40a5bcb4af2fe6898f3)"

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".dependencies.sha1]
discriminator = "sha1 0.1.0 (git+https://github.com/j1mbo64/sha1_cairo.git#2b65bc00a829bdcc244c140d0f31feda32f8d2c4)"

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".dependencies.shinigami_engine]
discriminator = "shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".dependencies.shinigami_utils]
discriminator = "shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.override."shinigami_engine 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"]
name = "shinigami_utils"
edition = "2024_07"
version = "0.1.0"

[config.override."shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".dependencies.shinigami_utils]
discriminator = "shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)"

[config.override."shinigami_utils 0.1.0 (git+https://github.com/keep-starknet-strange/shinigami.git?rev=1963116#1963116dc6f24eb32d0513c6394ad64da515ceff)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"]
name = "stwo_cairo_air"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    [
    "feature",
    "default",
],
    [
    "feature",
    "minimal_verifier",
],
    [
    "feature",
    "qm31_opcode",
],
    [
    "target",
    "executable",
],
]

[config.override."stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_cairo_air]
discriminator = "stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_cairo_air 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"]
name = "stwo_constraint_framework"
edition = "2024_07"
version = "0.1.0"

[config.override."stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_constraint_framework]
discriminator = "stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_constraint_framework 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"]
name = "stwo_verifier_core"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    [
    "feature",
    "default",
],
    [
    "feature",
    "qm31_opcode",
],
    [
    "target",
    "executable",
],
]

[config.override."stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.bounded_int]
discriminator = "bounded_int 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".dependencies.stwo_verifier_core]
discriminator = "stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)"

[config.override."stwo_verifier_core 0.1.0 (git+https://github.com/starkware-libs/stwo-cairo?rev=d09a2cfd2b308b6210906f26320f767cf279abef#d09a2cfd2b308b6210906f26320f767cf279abef)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

[config.override."utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)"]
name = "utils"
edition = "2024_07"
version = "0.1.0"
cfg_set = [
    [
    "feature",
    "default",
],
    [
    "feature",
    "syscalls",
],
    [
    "target",
    "executable",
],
]

[config.override."utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)".dependencies.utils]
discriminator = "utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)"

[config.override."utils 0.1.0 (path+file:///Users/michaelzaikin/raito/packages/utils/Scarb.toml)".experimental_features]
negative_impls = false
associated_item_constraints = false
coupons = false

