[files]
extend-exclude = [
    "docs/img/*.svg",      
    "docs/img/*.excalidraw",
    "bootloaders/simple_bootloader_compiled.json"
]

[default.extend-words]
Pn = "Pn"

[default]
extend-ignore-re = ["(?Rm)^.*(#|//)\\s*spellchecker:disable-line$"]
