---
- name: Manage Raito Bridge Node
  hosts: all
  become: yes
  vars:
    raito_working_dir: /home/raito/raito-bridge-node
    raito_user: raito
    raito_service_name: raito-bridge-node
    # Proof builder configuration
    proof_builder_user: maciej
    proof_builder_working_dir: /home/maciej/raito-prim
    raito_git_revision: "{{ lookup('env', 'RAITO_GIT_REVISION') | default('main') }}"
    bitcoin_rpc_url: "{{ lookup('env', 'BITCOIN_RPC') }}"
    bitcoin_rpc_userpwd: "{{ lookup('env', 'USERPWD') }}"
    rpc_host: "{{ lookup('env', 'RPC_HOST') | default('0.0.0.0:8080') }}"
    gcp_instance_name: "{{ lookup('env', 'GCP_INSTANCE_NAME') | default('raito') }}"
    gcp_environment: "{{ lookup('env', 'GCP_ENVIRONMENT') | default('production') }}"
    google_application_credentials: "{{ lookup('env', 'GOOGLE_APPLICATION_CREDENTIALS') | default('/home/' + raito_user + '/google-credentials.json') }}"

  tasks:
    - name: Include setup role
      import_role:
        name: setup
      tags: [setup, never]
      
    - name: Include start role
      import_role:
        name: start
      tags: [start, never]
      
    - name: Include update role
      import_role:
        name: update
      tags: [update, never]
      
    - name: Include stop role
      import_role:
        name: stop
      tags: [stop, never]
      
    - name: Include expose role
      import_role:
        name: expose
      tags: [expose, never]
      
    - name: Include fetch_db role
      import_role:
        name: fetch_db
      tags: [fetch-db, never]
